modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/aqariio/fowl-play/issues"
license = "MIT"

[[mods]]
modId = "fowlplay"
version = "${version}"
displayName = "Fowl Play"
description = '''
Just smile and wave, boys. Smile and wave.
'''
authors = "aqario"
credits = "Penguin60, Disketaa, owen233666, sanduicheirainox, Gnom1112"
logoFile = "assets/fowlplay/icon.png"
displayURL = "https://modrinth.com/mod/fowlplay"

[[dependencies.fowlplay]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "smartbrainlib"
type = "required"
versionRange = "[${sbl_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[${yacl_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "fowlplay.common.mixins.json"

[[mixins]]
config = "fowlplay.neoforge.mixins.json"

[mc-publish]
dependencies = [
    "architectury-api(recommended)",
    "yacl(recommended)",
]